[package]
name = "btc_wallet_mod"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/mod.rs"


[dependencies]
candid = "0.7.10"
ic-cdk = "0.5"
ic-cdk-macros = "0.5"
ic-types = "0.4.0"
serde = "1.0"
serde_json = "1.0"
serde_bytes = "0.11"
ego_lib = "0.1.9"